// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hhejcxsjjayzylrbdlcr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhoZWpjeHNqamF5enlscmJkbGNyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwMzY1MzYsImV4cCI6MjA1ODYxMjUzNn0.h4SJwsY0GvcBUOR6RDd3HCLTCnxxJB1hvq6rBQ8LJHQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);